version: "3.2"

services:
  bluegenes:
    container_name: agr.stage.bluegenes.server
    image: intermine/bluegenes:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "5000:5000"
    networks:
      - intermine
    env_file:
      - .env

  solr:
    container_name: agr.stage.alliancemine.solr.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_solr_env:stage
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "8983:8983"
    networks:
      - intermine
    env_file:
      - .env

  tomcat:
    container_name: agr.stage.alliancemine.tomcat.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_tomcat_env:stage
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "8080:8080"
    networks:
      - intermine
    env_file:
      - .env

  postgres:
    container_name: agr.stage.alliancemine.postgres.server
    image: intermine/postgres:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "5432:5432"
    networks:
      - intermine

#  loaddata:
#    depends_on:
#      bluegenes:
#      solr:
#      tomcat:
#      postgres:
#    container_name: agr.stage.alliancemine.loaddata
#    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_builder_env:stage
#    command: ./load_db_build_solr
#    logging:
#      driver: gelf
#      options:
#        gelf-address: 'udp://logs.alliancegenome.org:12201'
#    volumes:
#       - db_backup_volume:/root/data
#    networks:
#      - intermine
#    env_file:
#      - .env

networks:
  # The presence of these objects is sufficient to define them
  intermine:
